config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'home', to: 'pages#index', as: 'home'

  authenticated :user do
    root 'logins#index'
    get 'success' => 'logins#callback_success'

    resources :logins
    resources :accounts
    post 'create_login', to: 'logins#create_login', as: 'create_login'
    get 'list_logins', to: 'logins#list_logins', as: 'list_logins'
    post 'save_login', to: 'logins#save_login', as: 'save_login'
    delete 'remove_login', to: 'logins#remove_login', as: 'remove_login'
    put 'reconnect_login', to: 'logins#reconnect_login', as: 'reconnect_login'
    put 'refresh_login', to: 'logins#refresh_login', as: 'refresh_login'
    get 'fetch', to: 'accounts#fetch', as: 'fetch'
  end
  root to: "pages#index"
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :login, foreign_key: 'login_id'
  has_many :transactions, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/login.rb
class Login < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  has_many :accounts, dependent: :destroy

  validates :login_id, uniqueness: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account, foreign_key: 'account_id'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :logins

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def fetch
    login = Login.find_by(login_id: params[:login_id])

    login.accounts.destroy_all if login.accounts.any?
    response = Connector.fetch_accounts(login_id)

    accounts = JSON.parse response.body
    accounts = accounts['data']

    accounts.each do |account|
      transactions_posted  = account['extra']['transactions_count']['posted'].to_i
      transactions_pending = account['extra']['transactions_count']['pending'].to_i

      acc = Account.new(
        account_id:         account['id'],
        login_id:           login.id,
        name:               account['name'],
        balance:            account['balance'],
        currency:           account['currency_code'],
        nature:             account['nature'],
        transactions_count: transactions_posted + transactions_pending
      )
      acc.save

      fetch_transactions(acc_id, login.login_id)
    end
    redirect_to login
  end

  def show
    @account      = Account.find(params[:id])
    @transactions = @account.transactions
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_in_path_for(user)
    logins_path
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def index
    @logins = current_user.logins
  end

  def show
    @login    = Login.find(params[:id])
    @accounts = @login.accounts
  end

  def list
    user = User.find(current_user.id)

    user_logins = Connector.list_logins(user.customer_id)

    render json: user_logins
  end

  def create_login
    response    = Connector.connect_login(current_user.id)
    connect_url = response.dig("data","connect_url")

    flash.notice = 'Login successfully created'
    redirect_to connect_url
  rescue => error
    response = JSON.parse(error.response.body)
    flash.alert = response['error']['message']
    redirect_to logins_path
  end

  def callback_success
    save_login
    redirect_to logins_path
  end

  def save_login
    @user       = User.find(current_user.id)
    user_logins = Connector.list_logins(@user.customer_id)

    login = Login.new(
      user_id:                  @user.id,
      login_id:                 user_logins['data'].last['id'],
      country:                  user_logins['data'].last['country_code'],
      created_at:               user_logins['data'].last['created_at'],
      status:                   user_logins['data'].last['status'],
      provider:                 user_logins['data'].last['provider_name'],
      next_refresh_possible_at: user_logins['data'].last['next_refresh_possible_at']
    )
    login.save!

    fetch_all_accounts(login, user_logins['data'].last['id'])
  end

  def fetch_all_accounts(login, login_id)
    login.accounts.destroy_all if login.accounts.any?

    response = Connector.fetch_accounts(login_id)
    accounts = response.fetch("data")

    accounts.each do |account|
      transactions_posted  = account['extra']['transactions_count']['posted'].to_i
      transactions_pending = account['extra']['transactions_count']['pending'].to_i

      acc = Account.new(
        account_id:         account['id'],
        login_id:           login.id,
        name:               account['name'],
        balance:            account['balance'],
        currency:           account['currency_code'],
        nature:             account['nature'],
        transactions_count: transactions_posted + transactions_pending
      )

      acc.save!

      fetch_transactions(acc.id, acc.account_id, login.login_id)
    end
  end

  def fetch_transactions(acc_id, account_id, login_id)
    response     = Connector.fetch_transactions(login_id, account_id)
    transactions = response.fetch("data")

    transactions.each do |transaction|
      trans = Transaction.new(
        transaction_id: transaction['id'],
        status:         transaction['status'],
        currency:       transaction['currency_code'],
        amount:         transaction['amount'],
        description:    transaction['description'],
        made_on:        transaction['made_on'],
        category:       transaction['category'],
        account_id:     acc_id
      )

      trans.save!
    end
  end

  def reconnect_login
    response    = Connector.reconnect_login(params[:login_id])
    connect_url = response.dig("data", "connect_url")

    flash.notice = 'Login successfully reconnected'
    redirect_to connect_url
  rescue => error
    response = JSON.parse(error.response.body)
    flash.alert = response['error']['message']
    redirect_to logins_path
  end

  def refresh_login
    response    = Connector.refresh_login(params[:login_id])
    connect_url = response.dig("data", "connect_url")

    flash.notice = 'Login successfully refreshed'
    redirect_to connect_url
  rescue => error
    response = JSON.parse(error.response.body)
    flash.alert = response['error']['message']
    redirect_to logins_path
  end

  def remove_login
    Connector.remove_login(params[:login_id])

    Login.find_by(login_id: params[:login_id]).destroy

    redirect_to logins_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index; end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def fetch; end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def new
    super
  end

  def create
    super
    email = params[:user]["email"]
    user = User.find_by(email: email)

    response = Connector.create_customer(email)
    customer_id = response.dig("data", "id")
    user.customer_id = customer_id
    user.save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_account.html.erb
<tr>
  <th><%= account_id = account.account_id
          link_to account.account_id, account %>
  </th>
  <td><%= account.name %></td>
  <td><%= account.balance %></td>
  <td><%= account.currency %></td>
  <td><%= account.nature %></td>
  <td><%= account.transactions_count %></td>
</tr>

app/views/accounts/show.html.erb
<div class="container">
  <table class="table table-responsive">
    <thead class="thead-light">
      <tr>
        <th>ID</th>
        <th>Made On</th>
        <th>Status</th>
        <th>Category</th>
        <th>Description</th>
        <th>Amount</th>
        <th>Currency</th>
      </tr>
    </thead>
    <tbody>
      <%= render @transactions %>
    </tbody>
  </table>
</div>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-sm bg-light navbar-light">
  <% if user_signed_in? %>
  <ul class="navbar-nav">
    <li class="nav-item active nav-link">
      Signed in as <%= current_user.email %>
    </li>
    <li class="nav-item active">
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link"%>
    </li>
    <li class="nav-item active">
      <%= link_to "Create new login", create_login_path(current_user), method: :post, class: "nav-link"%>
    </li>
  </ul>
<% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpectreTestTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'navbar' %>
    <%= yield %>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
  </body>
</html>

app/views/logins/_login.html.erb
<tr>
  <th><%= link_to login.login_id, login %></th>
  <td>
    <%= user = User.find(login.user_id)
        customer_id = user.customer_id %>
  </td>
  <td><%= login.country %></td>
  <td><%= login.provider %></td>
  <td><%= login.status %></td>
  <td><%= login_id = login.login_id
          link_to 'Reconnect', reconnect_login_path(login_id: login_id), method: :put, class: "btn btn-outline-success btn-sm"%>
  </td>
  <td><%= link_to 'Refresh', refresh_login_path(login_id: login_id), method: :put, class: "btn btn-outline-primary btn-sm" %></td>
  <td><%= link_to 'Remove', remove_login_path(login_id: login_id), method: :delete, class: "btn btn-outline-danger btn-sm" %></td>
</tr>

app/views/logins/index.html.erb
<div class="container">
  <table class="table table-responsive">
    <thead class="thead-light">
      <th>ID</th>
      <th>Customer ID</th>
      <th>Country Code</th>
      <th>Provider</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </thead>
    <tbody>
      <%= render @logins %>
    </tbody>
  </table>
</div>

app/views/logins/show.html.erb
<div class="container">
  <table class="table table-responsive">
    <thead class="thead-light">
      <th>ID</th>
      <th>Name</th>
      <th>Balance</th>
      <th>Currency</th>
      <th>Nature</th>
      <th>Transactions</th>
    </thead>
    <tbody>
      <%= render @accounts %>
    </tbody>
  </table>
</div>

app/views/pages/index.html.erb
<div class="container p-3 my-3 border">
  <h2 class="text-center">Spectre Test Task</h2>
  <p class="card-text text-center">
    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-outline-success btn-fixed"%>
    <%= link_to "Sign In", new_user_session_path, class: "btn btn-outline-success btn-fixed"%>
  </p>
</div>

app/views/transactions/_transaction.html.erb
<tr>
  <td><%= transaction.transaction_id %></td>
  <td><%= transaction.made_on %></td>
  <td><%= transaction.status %></td>
  <td><%= transaction.category %></td>
  <td><%= transaction.description %></td>
  <td><%= transaction.amount %></td>
  <td><%= transaction.currency %></td>
</tr>